apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orderflow-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BahriniHoussem001/devops-orderflow-microservices.git
    targetRevision: feat/k8s-manifests
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: orderflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true