apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orderflow

resources:
  - namespace.yaml
  - order-postgres.yaml
  - notification-postgres.yaml
  - rabbitmq.yaml
  - order-service.yaml
  - notification-service.yaml
  - order-service-nodeport.yaml
  - notification-service-nodeport.yaml