apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-postgres
  namespace: orderflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-postgres
  template:
    metadata:
      labels:
        app: notification-postgres
    spec:
      containers:
        - name: notification-postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: notifications_db
---
apiVersion: v1
kind: Service
metadata:
  name: notification-postgres
  namespace: orderflow
spec:
  selector:
    app: notification-postgres
  ports:
    - port: 5432
      targetPort: 5432