name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
      - feat/**
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add .NET tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Begin SonarCloud analysis
        run: >
          dotnet sonarscanner begin
          /k:"BahriniHoussem001_devops-orderflow-microservices"
          /o:"bahrinihoussem001"
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          /d:sonar.host.url="https://sonarcloud.io"

      - name: Restore OrderService dependencies
        run: dotnet restore ./OrderService.Api/OrderService.Api.csproj

      - name: Build OrderService
        run: dotnet build ./OrderService.Api/OrderService.Api.csproj --no-restore --configuration Release

      - name: Restore NotificationService dependencies
        run: dotnet restore ./NotificationService.Api/NotificationService.Api.csproj

      - name: Build NotificationService
        run: dotnet build ./NotificationService.Api/NotificationService.Api.csproj --no-restore --configuration Release

      - name: Check Docker Hub secrets
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "DOCKERHUB_USERNAME is empty"
            exit 1
          else
            echo "DOCKERHUB_USERNAME is set"
          fi

          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "DOCKERHUB_TOKEN is empty"
            exit 1
          else
            echo "DOCKERHUB_TOKEN is set"
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image for OrderService
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/orderservice:latest ./OrderService.Api

      - name: Build Docker image for NotificationService
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/notificationservice:latest ./NotificationService.Api

      - name: Push OrderService image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/orderservice:latest

      - name: Push NotificationService image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/notificationservice:latest

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan OrderService image with Trivy
        run: trivy image --severity HIGH,CRITICAL --exit-code 0 ${{ secrets.DOCKERHUB_USERNAME }}/orderservice:latest

      - name: Scan NotificationService image with Trivy
        run: trivy image --severity HIGH,CRITICAL --exit-code 0 ${{ secrets.DOCKERHUB_USERNAME }}/notificationservice:latest

      - name: End SonarCloud analysis
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"